=== aryarya007/TugasWebServiceBab4/Pendidikan.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="Pendidikan">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="Mahasiswa"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Mahasiswa">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="DataDiri"/>
                <xs:element ref="Studi"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="DataDiri">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="NPM" minOccurs="1"/>
                <xs:element ref="Nama"/>
                <xs:element ref="JK"/>
                <xs:element ref="Alamat"/>
                <xs:element ref="AsalDaerah"/>
                <xs:element ref="Usia"/>
                <xs:element ref="Agama"/>
                <xs:element ref="E-mail"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="NPM" type="xs:integer"/>
    <xs:element name="Nama" type="xs:NCName"/>
    <xs:element name="JK">
    	<xs:simpleType>
    		<xs:restriction base="xs:NCName">
    		</xs:restriction>
    	</xs:simpleType>
    </xs:element>
    <xs:element name="Alamat" type="xs:NCName"/>
    <xs:element name="AsalDaerah" type="xs:NCName"/>
    <xs:element name="Usia" type="xs:string"/>
    <xs:element name="Agama" type="xs:NCName"/>
    <xs:element name="E-mail">
    	<xs:simpleType>
    		<xs:restriction base="xs:string">
    			<xs:pattern
    				value="([0-9a-zA-Z]([-.\w]*[0-9a-zA-Z])*@([0-9a-zA-Z][-\w]*[0-9a-zA-Z]\.)+[a-zA-Z]{2,9})">
    			</xs:pattern>
    		</xs:restriction>
    	</xs:simpleType>
    </xs:element>
    <xs:element name="Studi">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Jurusan"/>
                <xs:element ref="Prodi"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Jurusan" type="xs:string"/>
    <xs:element name="Prodi" type="xs:NCName"/>
</xs:schema>

=== aryarya007/TugasWebServiceBab4/Pendidikan.xml
<?xml version="1.0" encoding="UTF-8"?>
<Pendidikan xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Pendidikan.xsd">
	<Mahasiswa>
		<DataDiri>
			<NPM>1154075</NPM>
			<Nama>Arya</Nama>
			<JK>Pria</JK>
			<Alamat>Sarijadi</Alamat>
			<AsalDaerah>Tarutung</AsalDaerah>
			<Usia>20 Tahun</Usia>
			<Agama>Islam</Agama>
			<E-mail>arya.mohammad00@gmail.com</E-mail>
		</DataDiri>
		<Studi>
			<Jurusan>Teknik Informatika</Jurusan>
			<Prodi>D4</Prodi>
		</Studi>
	</Mahasiswa>
	
	<Mahasiswa>
		<DataDiri>
			<NPM>1154024</NPM>
			<Nama>Adam</Nama>
			<JK>Pria</JK>
			<Alamat>Sarijadi</Alamat>
			<AsalDaerah>Salatiga</AsalDaerah>
			<Usia>20 Tahun</Usia>
			<Agama>Islam</Agama>
			<E-mail>adam.mohammad00@gmail.com</E-mail>
		</DataDiri>
		<Studi>
			<Jurusan>Teknik Informatika</Jurusan>
			<Prodi>D4</Prodi>
		</Studi>
	</Mahasiswa>
	
	<Mahasiswa>
		<DataDiri>
			<NPM>1154094</NPM>
			<Nama>Akbar</Nama>
			<JK>Pria</JK>
			<Alamat>Sarijadi</Alamat>
			<AsalDaerah>Sinjai</AsalDaerah>
			<Usia>20 Tahun</Usia>
			<Agama>Islam</Agama>
			<E-mail>akbar.mohammad00@gmail.com</E-mail>
		</DataDiri>
		<Studi>
			<Jurusan>Teknik Informatika</Jurusan>
			<Prodi>D4</Prodi>
		</Studi>
	</Mahasiswa>
	
	<Mahasiswa>
		<DataDiri>
			<NPM>1154068</NPM>
			<Nama>Julham</Nama>
			<JK>Pria</JK>
			<Alamat>Sarijadi</Alamat>
			<AsalDaerah>Tarutung</AsalDaerah>
			<Usia>20 Tahun</Usia>
			<Agama>Islam</Agama>
			<E-mail>arya.mohammad00@gmail.com</E-mail>
		</DataDiri>
		<Studi>
			<Jurusan>Teknik Informatika</Jurusan>
			<Prodi>D4</Prodi>
		</Studi>
	</Mahasiswa>
	
	<Mahasiswa>
		<DataDiri>
			<NPM>1154074</NPM>
			<Nama>Tito</Nama>
			<JK>Pria</JK>
			<Alamat>Sarijadi</Alamat>
			<AsalDaerah>Depok</AsalDaerah>
			<Usia>20 Tahun</Usia>
			<Agama>Islam</Agama>
			<E-mail>tito.mohammad00@gmail.com</E-mail>
		</DataDiri>
		<Studi>
			<Jurusan>Teknik Informatika</Jurusan>
			<Prodi>D4</Prodi>
		</Studi>
	</Mahasiswa>
</Pendidikan>
